dbConfig:
  host: "127.0.0.1"
  database: "your-db-name"
  user: "root"

redisConfig:
  host: "127.0.0.1"

aws:
  accessKeyId: "<accessKeyId>"
  secretAccessKey: "<secretAccessKey>"
  region: "ap-northeast-1"

slack:
  hook_url: "http://localhost"
  channel: "#your-channel-name"
  botname: "your-bot-name"
  mention: "<your-account-name>"

bucketName: "buckt-name"

gameTimeSec: 180
startMarginSec: 10
checkConnIntervalSec: 0.3
checkTimesLimit: 30
forceDoneTimeSec: 10
revengeForceStartTimeSec: 0.7
waitForClientReadySec: 0.01
repeatForOvercomingPacketLoss: 3

addMatchingThresholdNumForExtra: 20
intervalForLoadBalancingSec: 0.6
intervalForAutoscalingSec: 30
intervalForHostInfoUpdateSec: 30
cfnStackName: "stack-name"
ec2HostTag: "^ec2-tag-name"
ec2HostTagForLobby: "^ec2-tag-name-for-lobby$"
ec2HostTagForGame: "^ec2-tag-name-for-game$"
redHostThreshold: 350
minimumGreenHostsNum: 2
connNumForRedHost: 999999
redisKeyForLobbyLoadbalancing: "redis-key-for-lobby"
redisKeyForGameLoadbalancing: "redis-key-for-game"
scaleOutThreshold: 20
scaleInThreshold: 3
scaleOutMinimumIntervalSec: 180
scaleInMinimumIntervalSec: 3600
autoRestartCpuUsageThresholdForApp: 10
autoRestartCpuUsageThresholdForLB: 80
autoRestartMonitorIntervalSec: 15
resetLbKeysRoutineIntervalSec: 180
scaleInAvailableStartAt: 4
scaleInAvailableEndAt: 5
serverTypeNum: 2
kumogataUpdateCmd: "cloudformation-update-cmd"
restartCmd: "restart-cmd"
notifyRoomNumMessage: "message-by-slack"

monitoredHost: "ec2-__-__-__-__.ap-northeast-1.compute.amazonaws.com"
monitoredProcess: "game"
monitoringIntervalSec: 30
decisionIntervalSec: 120
