redisConfig:
  host: "127.0.0.1"

aws:
  accessKeyId: "<accessKeyId>"
  secretAccessKey: "<secretAccessKey>"
  region: "ap-northeast-1"

slack:
  hook_url: "http://localhost"
  channel: "#your-channel-name"
  botname: "your-bot-name"
  mention: "<your-account-name>"

# for schedulerMonitor
monitoredHost: "ec2-__-__-__-__.ap-northeast-1.compute.amazonaws.com"
monitoredProcess: "game"
monitoringIntervalSec: 30
decisionIntervalSec: 120

# for loadbalancing
redHostThreshold: 350
connNumForRedHost: 999999
ec2HostTagForLobby: "^ec2-tag-name-for-lobby$"
ec2HostTagForGame: "^ec2-tag-name-for-game$"
intervalForLoadBalancingSec: 0.6
intervalForAutoscalingSec: 30
intervalForHostInfoUpdateSec: 30
redisKeyForLobbyLoadbalancing: "redis-key-for-lobby"
redisKeyForGameLoadbalancing: "redis-key-for-game"

# for autoscaling
restartCmd: "restart-cmd"
cfnStackName: "stack-name"
serverTypeNum: 2
scaleOutThreshold: 20
scaleInThreshold: 3
kumogataUpdateCmd: "cloudformation-update-cmd"
minimumGreenHostsNum: 2
forceScaleOutStartAt: 18
forceScaleOutEndAt: 23
scaleInAvailableStartAt: 4
scaleInAvailableEndAt: 5
notifyRoomNumMessage: "message-by-slack"
scaleInMinimumIntervalSec: 3600
scaleOutMinimumIntervalSec: 180
specifiedTimeGreenHostsNum: 40
autoRestartMonitorIntervalSec: 15
resetLbKeysRoutineIntervalSec: 180
autoRestartCpuUsageThresholdForLB: 80
autoRestartCpuUsageThresholdForApp: 10
